blank_issues_enabled: false

contact_links:
  - name: Mytoml | TOML for Modern C/C++ ğŸ“š
    url: https://github.com/djoezeke/mytoml
    about: Simple and Fast Tom's Obvious Markup Language (TOML) Parser for Modern C/C++.

  - name: Mytoml Discussions ğŸ’–
    url: https://github.com/djoezeke/mytoml/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Mytoml Issues | Bug Bounty ğŸ
    url: https://github.com/djoezeke/mytoml/issues
    about: Please report issues and vulnerabilities here.

  - name: Mytoml Releases & Tags ğŸ“¦
    url: https://github.com/djoezeke/mytoml/releases
    about: Please latest Mytoml release here.

  - name: Mytoml Documentation ğŸ“š
    url: https://djoezeke.github.io/mytoml/
    about: Please refer to the Mytoml documentation here.
